/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizsueli;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Thayson
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        this.setBounds(WIDTH, WIDTH, 1100, 687);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nomes = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jogador2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jogador1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Fundo1 = new javax.swing.JLabel();
        Tabuleiro = new javax.swing.JFrame();
        jog2 = new javax.swing.JLabel();
        jog1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jogadordois1 = new javax.swing.JLabel();
        jogadordois2 = new javax.swing.JLabel();
        jogadorum2 = new javax.swing.JLabel();
        jogadordois3 = new javax.swing.JLabel();
        jogadordois5 = new javax.swing.JLabel();
        jogadorum3 = new javax.swing.JLabel();
        jogadordois4 = new javax.swing.JLabel();
        jogadorum4 = new javax.swing.JLabel();
        jogadorum5 = new javax.swing.JLabel();
        jogadorum6 = new javax.swing.JLabel();
        jogadordois6 = new javax.swing.JLabel();
        jogadorum1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        Fundo2 = new javax.swing.JLabel();
        Pergunta = new javax.swing.JFrame();
        jButton5 = new javax.swing.JButton();
        vezde = new javax.swing.JLabel();
        p1 = new javax.swing.JRadioButton();
        p2 = new javax.swing.JRadioButton();
        p3 = new javax.swing.JRadioButton();
        p4 = new javax.swing.JRadioButton();
        p5 = new javax.swing.JRadioButton();
        pergunta = new javax.swing.JLabel();
        Fundo3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Vencedor = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        v = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        Nomes.getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jogador 2:");
        Nomes.getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 360, 160, 50);

        jogador2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jogador2.setText("Digite seu nome!");
        jogador2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jogador2MouseClicked(evt);
            }
        });
        Nomes.getContentPane().add(jogador2);
        jogador2.setBounds(450, 370, 330, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jogador 1:");
        Nomes.getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 260, 160, 50);

        jogador1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jogador1.setText("Digite seu nome!");
        jogador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jogador1MouseClicked(evt);
            }
        });
        Nomes.getContentPane().add(jogador1);
        jogador1.setBounds(450, 270, 330, 30);

        jButton3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButton3.setText("Próximo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Nomes.getContentPane().add(jButton3);
        jButton3.setBounds(450, 490, 150, 70);

        jLabel5.setBackground(new java.awt.Color(0, 0, 255));
        jLabel5.setFont(new java.awt.Font("DialogInput", 0, 100)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quiz Sueli");
        Nomes.getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 70, 660, 100);

        Fundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/a.png"))); // NOI18N
        Nomes.getContentPane().add(Fundo1);
        Fundo1.setBounds(0, 0, 1100, 687);

        Tabuleiro.getContentPane().setLayout(null);

        jog2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jog2.setForeground(new java.awt.Color(255, 255, 255));
        Tabuleiro.getContentPane().add(jog2);
        jog2.setBounds(760, 190, 130, 50);

        jog1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jog1.setForeground(new java.awt.Color(255, 255, 255));
        Tabuleiro.getContentPane().add(jog1);
        jog1.setBounds(210, 190, 130, 50);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Tabuleiro.getContentPane().add(jSeparator1);
        jSeparator1.setBounds(520, 190, 10, 380);
        Tabuleiro.getContentPane().add(jSeparator2);
        jSeparator2.setBounds(10, 240, 1060, 10);

        jLabel3.setBackground(new java.awt.Color(0, 0, 255));
        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 100)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quiz Sueli");
        Tabuleiro.getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 80, 660, 100);

        jogadordois1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.png"))); // NOI18N
        Tabuleiro.getContentPane().add(jogadordois1);
        jogadordois1.setBounds(590, 270, 70, 70);

        jogadordois2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.png"))); // NOI18N
        Tabuleiro.getContentPane().add(jogadordois2);
        jogadordois2.setBounds(750, 270, 70, 70);

        jogadorum2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.png"))); // NOI18N
        Tabuleiro.getContentPane().add(jogadorum2);
        jogadorum2.setBounds(230, 270, 70, 70);

        jogadordois3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.png"))); // NOI18N
        Tabuleiro.getContentPane().add(jogadordois3);
        jogadordois3.setBounds(910, 270, 70, 70);

        jogadordois5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.png"))); // NOI18N
        Tabuleiro.getContentPane().add(jogadordois5);
        jogadordois5.setBounds(750, 430, 70, 70);

        jogadorum3.setBackground(new java.awt.Color(0, 102, 255));
        jogadorum3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.png"))); // NOI18N
        Tabuleiro.getContentPane().add(jogadorum3);
        jogadorum3.setBounds(380, 270, 70, 70);

        jogadordois4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.png"))); // NOI18N
        Tabuleiro.getContentPane().add(jogadordois4);
        jogadordois4.setBounds(590, 430, 70, 70);

        jogadorum4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.png"))); // NOI18N
        Tabuleiro.getContentPane().add(jogadorum4);
        jogadorum4.setBounds(80, 430, 70, 70);

        jogadorum5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.png"))); // NOI18N
        Tabuleiro.getContentPane().add(jogadorum5);
        jogadorum5.setBounds(230, 430, 70, 70);

        jogadorum6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.png"))); // NOI18N
        Tabuleiro.getContentPane().add(jogadorum6);
        jogadorum6.setBounds(380, 430, 70, 70);

        jogadordois6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.png"))); // NOI18N
        Tabuleiro.getContentPane().add(jogadordois6);
        jogadordois6.setBounds(920, 430, 70, 70);

        jogadorum1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.png"))); // NOI18N
        Tabuleiro.getContentPane().add(jogadorum1);
        jogadorum1.setBounds(80, 270, 70, 70);

        jButton4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton4.setText("Pergunta");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        Tabuleiro.getContentPane().add(jButton4);
        jButton4.setBounds(420, 580, 220, 50);

        Fundo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/a.png"))); // NOI18N
        Tabuleiro.getContentPane().add(Fundo2);
        Fundo2.setBounds(0, 0, 1100, 687);

        Pergunta.setSize(new java.awt.Dimension(1016, 595));
        Pergunta.getContentPane().setLayout(null);

        jButton5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton5.setText("Ok");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        Pergunta.getContentPane().add(jButton5);
        jButton5.setBounds(280, 400, 130, 50);

        vezde.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        vezde.setForeground(new java.awt.Color(0, 102, 102));
        vezde.setText("Vez:");
        Pergunta.getContentPane().add(vezde);
        vezde.setBounds(50, 480, 490, 50);

        p1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(p1);
        p1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        p1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Pergunta.getContentPane().add(p1);
        p1.setBounds(0, 110, 620, 23);

        p2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(p2);
        p2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Pergunta.getContentPane().add(p2);
        p2.setBounds(0, 160, 620, 23);

        p3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(p3);
        p3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Pergunta.getContentPane().add(p3);
        p3.setBounds(0, 210, 620, 23);

        p4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(p4);
        p4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Pergunta.getContentPane().add(p4);
        p4.setBounds(0, 260, 620, 23);

        p5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(p5);
        p5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Pergunta.getContentPane().add(p5);
        p5.setBounds(0, 310, 620, 23);

        pergunta.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Pergunta.getContentPane().add(pergunta);
        pergunta.setBounds(20, 0, 990, 60);
        Pergunta.getContentPane().add(Fundo3);
        Fundo3.setBounds(0, 0, 1120, 560);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/6827487-zelda-wallpaper.jpg"))); // NOI18N
        Pergunta.getContentPane().add(jLabel7);
        jLabel7.setBounds(-6, -6, 1016, 550);

        Vencedor.getContentPane().setLayout(null);

        jLabel8.setBackground(new java.awt.Color(0, 0, 255));
        jLabel8.setFont(new java.awt.Font("DialogInput", 0, 100)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("VENCEDOR");
        Vencedor.getContentPane().add(jLabel8);
        jLabel8.setBounds(150, 20, 490, 100);
        Vencedor.getContentPane().add(jSeparator3);
        jSeparator3.setBounds(20, 250, 740, 10);

        v.setBackground(new java.awt.Color(0, 0, 255));
        v.setFont(new java.awt.Font("DialogInput", 0, 80)); // NOI18N
        v.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Vencedor.getContentPane().add(v);
        v.setBounds(120, 150, 540, 90);

        jButton6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton6.setText("Menu Principal");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Vencedor.getContentPane().add(jButton6);
        jButton6.setBounds(310, 290, 160, 50);
        Vencedor.getContentPane().add(jSeparator4);
        jSeparator4.setBounds(100, 120, 590, 10);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/as.png"))); // NOI18N
        Vencedor.getContentPane().add(jLabel9);
        jLabel9.setBounds(170, 360, 100, 90);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/as.png"))); // NOI18N
        Vencedor.getContentPane().add(jLabel10);
        jLabel10.setBounds(540, 360, 100, 90);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/4.jpg"))); // NOI18N
        Vencedor.getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 800, 450);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiz Sueli");
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButton1.setText("Jogar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 320, 150, 70);

        jButton2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(660, 320, 150, 70);

        jLabel2.setBackground(new java.awt.Color(0, 0, 255));
        jLabel2.setFont(new java.awt.Font("DialogInput", 0, 100)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quiz Sueli");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 80, 660, 100);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/a.png"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, 0, 1100, 687);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair da aplicação?");

        if (sair == 0) {
            System.exit(0);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Nomes.setBounds(WIDTH, WIDTH, 1100, 687);
        Nomes.setVisible(true);
        this.setVisible(false);
        Nomes.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jogador1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jogador1MouseClicked
        if (evt.getClickCount() == 1) {
            jogador1.setText("");
        }
    }//GEN-LAST:event_jogador1MouseClicked

    private void jogador2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jogador2MouseClicked
        if (evt.getClickCount() == 1) {
            jogador2.setText("");
        }
    }//GEN-LAST:event_jogador2MouseClicked
    String play1, play2, j1, j2 = null;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        play1 = jogador1.getText();
        play2 = jogador2.getText();

        j1 = jogador1.getText();
        j2 = jogador2.getText();

        if (play1.equals("Digite seu nome!") || play2.equals("Digite seu nome!") || play1.equals("") || play2.equals("")) {
            JOptionPane.showMessageDialog(null, "Jogadores digitem seus nomes!");
        } else {

            Tabuleiro.setBounds(WIDTH, WIDTH, 1100, 687);

            jog2.setText(play2.toUpperCase());
            jog1.setText(play1.toUpperCase());

            Tabuleiro.setVisible(true);
            Nomes.setVisible(false);
            Tabuleiro.setLocationRelativeTo(null);
        }

    }//GEN-LAST:event_jButton3ActionPerformed
    int vez = 1;
    int jogadorUm = 0, jogadorDois = 0;
    boolean cara1 = false, cara2 = false;
    String resposta;
    String linhacerta;
    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        p1.setOpaque(false);
        p1.setContentAreaFilled(false);
        p1.setBorderPainted(false);

        p2.setOpaque(false);
        p2.setContentAreaFilled(false);
        p2.setBorderPainted(false);

        p3.setOpaque(false);
        p3.setContentAreaFilled(false);
        p3.setBorderPainted(false);

        p4.setOpaque(false);
        p4.setContentAreaFilled(false);
        p4.setBorderPainted(false);

        p5.setOpaque(false);
        p5.setContentAreaFilled(false);
        p5.setBorderPainted(false);

        if (vez % 2 == 0) {
            vezde.setText("Vez: " + play2.toUpperCase());
            cara2 = true;
        } else {
            vezde.setText("Vez: " + play1.toUpperCase());
            cara1 = true;
        }

        String linha;
        BufferedReader conexao = null;

        Gerar();
        VerificarPergunta();
        
        try {
            conexao = new BufferedReader(new FileReader("perguntas.txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            while ((linha = conexao.readLine()) != null) {

                String a[] = linha.split(";");

                if (a[0].equals(linhacerta)) {
                    pergunta.setText(a[1]);

                    p1.setText(a[2]);
                    p2.setText(a[3]);
                    p3.setText(a[4]);
                    p4.setText(a[5]);
                    p5.setText(a[6]);
                    resposta = a[7];
                }
            }
            conexao.close();
        } catch (IOException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }

        Pergunta.setBounds(WIDTH, WIDTH, 1009, 571);
        Pergunta.setVisible(true);
        Pergunta.setLocationRelativeTo(null);

        vez++;
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        if (cara1) {
            if (p1.isSelected() && resposta.equals("1")) {
                jogadorUm++;
            } else {
                if (p2.isSelected() && resposta.equals("2")) {
                    jogadorUm++;
                } else {
                    if (p3.isSelected() && resposta.equals("3")) {
                        jogadorUm++;
                    } else {
                        if (p4.isSelected() && resposta.equals("4")) {
                            jogadorUm++;
                        } else {
                            if (p5.isSelected() && resposta.equals("5")) {
                                jogadorUm++;
                            }
                        }
                    }
                }
            }
            cara1 = false;
        }

        if (cara2) {
            if (p1.isSelected() && resposta.equals("1")) {
                jogadorDois++;
            } else {
                if (p2.isSelected() && resposta.equals("2")) {
                    jogadorDois++;
                } else {
                    if (p3.isSelected() && resposta.equals("3")) {
                        jogadorDois++;
                    } else {
                        if (p4.isSelected() && resposta.equals("4")) {
                            jogadorDois++;
                        } else {
                            if (p5.isSelected() && resposta.equals("5")) {
                                jogadorDois++;
                            }
                        }
                    }
                }
            }
            cara2 = false;
        }

        buttonGroup1.clearSelection();

        carregarFotos();

        Pergunta.setVisible(false);
        Tabuleiro.setVisible(true);
        ganhou();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();

        Tela t = new Tela();
        t.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }
    
    String perguntaAnt;
    
    String Gerar() {
        int LerLinha = (int) (Math.random() * 41);

        if (LerLinha == 0) {
            LerLinha = (int) (Math.random() * 41);
        }
        
        linhacerta = LerLinha + "";
        
        return linhacerta;
    }
    
    private void Receber(){
        
    }
    
    public void VerificarPergunta() {
     
    }

    void carregarFotos() {
        if (jogadorUm == 1) {
            jogadorum1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/paper.png")));
        }

        if (jogadorUm == 2) {
            jogadorum2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/paper.png")));
        }

        if (jogadorUm == 3) {
            jogadorum3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/paper.png")));
        }

        if (jogadorUm == 4) {
            jogadorum4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/paper.png")));
        }

        if (jogadorUm == 5) {
            jogadorum5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/paper.png")));
        }

        if (jogadorUm == 6) {
            jogadorum6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/paper.png")));
        }

        // sessão jogador 2
        if (jogadorDois == 1) {
            jogadordois1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/paper.png")));
        }

        if (jogadorDois == 2) {
            jogadordois2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/paper.png")));
        }

        if (jogadorDois == 3) {
            jogadordois3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/paper.png")));
        }

        if (jogadorDois == 4) {
            jogadordois4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/paper.png")));
        }

        if (jogadorDois == 5) {
            jogadordois5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/paper.png")));
        }

        if (jogadorDois == 6) {
            jogadordois6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/paper.png")));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Fundo1;
    private javax.swing.JLabel Fundo2;
    private javax.swing.JLabel Fundo3;
    private javax.swing.JFrame Nomes;
    private javax.swing.JFrame Pergunta;
    private javax.swing.JFrame Tabuleiro;
    private javax.swing.JFrame Vencedor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel jog1;
    private javax.swing.JLabel jog2;
    private javax.swing.JTextField jogador1;
    private javax.swing.JTextField jogador2;
    private javax.swing.JLabel jogadordois1;
    private javax.swing.JLabel jogadordois2;
    private javax.swing.JLabel jogadordois3;
    private javax.swing.JLabel jogadordois4;
    private javax.swing.JLabel jogadordois5;
    private javax.swing.JLabel jogadordois6;
    private javax.swing.JLabel jogadorum1;
    private javax.swing.JLabel jogadorum2;
    private javax.swing.JLabel jogadorum3;
    private javax.swing.JLabel jogadorum4;
    private javax.swing.JLabel jogadorum5;
    private javax.swing.JLabel jogadorum6;
    private javax.swing.JRadioButton p1;
    private javax.swing.JRadioButton p2;
    private javax.swing.JRadioButton p3;
    private javax.swing.JRadioButton p4;
    private javax.swing.JRadioButton p5;
    private javax.swing.JLabel pergunta;
    private javax.swing.JLabel v;
    private javax.swing.JLabel vezde;
    // End of variables declaration//GEN-END:variables

    private void ganhou() {
        if (jogadorUm == 6) {
            Vencedor.setBounds(WIDTH, WIDTH, 816, 485);
            v.setText(play1.toUpperCase());
            Vencedor.setVisible(true);
            Vencedor.setLocationRelativeTo(null);
        }

        if (jogadorDois == 6) {
            Vencedor.setBounds(WIDTH, WIDTH, 816, 485);
            v.setText(play2.toUpperCase());
            Vencedor.setVisible(true);
            Vencedor.setLocationRelativeTo(null);
        }
    }
}
